export const TITLE_CHANGE = 'TITLE_CHANGE';
export const TEXT_CHANGE = 'TEXT_CHANGE';
export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';