export const TITLE_CHANGE = 'TITLE_CHANGE';
export const TEXT_CHANGE = 'TEXT_CHANGE';
export const TODOS_FETCH_SUCCESS = 'TODOS_FETCH_SUCCESS';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const SEARCH_TERM_CHANGE = 'SEARCH_TERM_CHANGE';
export const TODOS_SEARCH = 'TODOS_SEARCH';
export const TOGGLE_COMPLETE = 'TOGGLE_COMPLETE';